upstream blue {
    server 127.0.0.1:3000;
}

upstream green {
    server 127.0.0.1:3001;
}

server {
    listen 80;

    location / {
        proxy_pass http://blue;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
